# ============================================================================
# Score 8 FE/BYM2 sim-study models on each of NSIM populations generated by
# either the SPDE or BYM2 generative model. Built on testInfrastructure.R for
# model-tagged file paths (intPtsDHS / simPopsSurveys).
#
# Per (sim, model) pair, the following score sets are saved:
#   - scoresFE     : fixed effects against the DGP truth (TRUE_FE)
#   - scoresHyper  : hyperparameters (sigma_BYM2, phi, sigma_eps) against truths
#   - scoresArea   : admin1 prevalences against areaPops[, sim]
#   - fitTime, scoreTime : minutes
# Subarea-level scoring was removed for speed (predGrid is the bottleneck).
# Output dir:  savedOutput/simStudy1/scores/<MODEL>/scores_<modName>_sim<i>.RData
# Summary:    savedOutput/simStudy1/scores/<MODEL>/scoresSummary.RData
#
# Entry points:
#   scoreSimStudy        (model, nsim, ...)            — serial
#   scoreSimStudyParallel(model, nsim, ..., nWorkers)  — callr worker pool
# ============================================================================

# Single source of truth for the posterior-draws strategy. The .postDraws
# wrapper below routes through this; default is "auto" (Gaussian, fall back
# to INLA-style if jointPrecision is non-PSD).
if(!exists("posteriorDraws")) source("code/inlaStyleDraws.R")

# DGP truth (shared by both generative models — same fixed effects)
TRUE_FE <- c(alpha                = -1.25,
             beta_urban           =  1.0,
             beta_access          =  0.0,
             beta_elev            =  0.0,
             beta_distRiversLakes =  0.0,
             beta_normPop         =  0.5)

MODELS <- c("Md_FE",  "Md",
            "M_D_FE", "M_M_FE",  "M_DM_FE",
            "M_D_BYM2", "M_M_BYM2", "M_DM_BYM2")

# Pick the area-level truth vector to score against. predGrid() produces
# pixel-level smooth (nugget-integrated) risk aggregated to area, so the
# consistent default is the smooth-risk truth field stored by the updated
# simData1*. Falls back to fine-scale prevalence (the historical default)
# if the simulated populations file doesn't carry the new smooth-risk field
# yet — useful for old simPopsSurveys_*.RData caches.
.pickAreaTruth <- function(simEnv, truthQuantity = c("smoothRisk", "fineScalePrevalence")) {
    truthQuantity <- match.arg(truthQuantity)
    if(truthQuantity == "smoothRisk") {
        if(!is.null(simEnv$areaPops_smoothRisk)) {
            return(simEnv$areaPops_smoothRisk)
        }
        warning("[scoreSimStudy] truthQuantity = \"smoothRisk\" requested but ",
                "simEnv$areaPops_smoothRisk is NULL — falling back to ",
                "fineScalePrevalence. Re-simulate with the updated simData1* ",
                "to produce smooth-risk truths.")
    }
    simEnv$areaPops
}

# ---- model fitting dispatch -------------------------------------------------
# Md / Md_FE collapse positional uncertainty to K=1 (cluster-center only).
.makeMdInputs <- function(inputsMDM) {
    inp <- inputsMDM
    inp$intPtsDHS$wUrban[, 1] <- 1; inp$intPtsDHS$wUrban[, -1] <- 0
    inp$intPtsDHS$wRural[, 1] <- 1; inp$intPtsDHS$wRural[, -1] <- 0
    inp
}

.fitOne <- function(modName, inp, KMICS, KDHSu, KDHSr, Qgh, COVS) {
    switch(modName,
        Md_FE     = fitFED (datDHS=inp$datDHS, inputsMDM=.makeMdInputs(inp$inputsMDM),
                            covariates=COVS, Qgh=Qgh, fixedEffectsOnly=TRUE,
                            getSDs=TRUE, verbose=FALSE),
        Md        = fitMd  (datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            KMICS=KMICS, KDHSurb=KDHSu, KDHSrur=KDHSr,
                            verbose=FALSE),
        M_D_FE    = fitFED (datDHS=inp$datDHS, inputsMDM=inp$inputsMDM,
                            covariates=COVS, Qgh=Qgh, fixedEffectsOnly=TRUE,
                            getSDs=TRUE, verbose=FALSE),
        M_M_FE    = fitFEM (datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            covariates=COVS, KMICS=KMICS, Qgh=Qgh, fixedEffectsOnly=TRUE,
                            getSDs=TRUE, verbose=FALSE),
        M_DM_FE   = fitFEMD(datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            covariates=COVS, KMICS=KMICS, Qgh=Qgh, fixedEffectsOnly=TRUE,
                            getSDs=TRUE, verbose=FALSE),
        M_D_BYM2  = fitMD  (datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            KMICS=KMICS, KDHSurb=KDHSu, KDHSrur=KDHSr,
                            Qgh=Qgh, getSDs=TRUE, verbose=FALSE),
        M_M_BYM2  = fitMM  (datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            KMICS=KMICS, Qgh=Qgh, getSDs=TRUE, verbose=FALSE),
        M_DM_BYM2 = fitMDM (datDHS=inp$datDHS, datMICS=inp$datMICS, inputsMDM=inp$inputsMDM,
                            KMICS=KMICS, KDHSurb=KDHSu, KDHSrur=KDHSr,
                            Qgh=Qgh, getSDs=TRUE, verbose=FALSE))
}

# ---- posterior draws -------------------------------------------------------
# Single entry point: routes through posteriorDraws() in inlaStyleDraws.R.
# Default (useInla = "auto"): joint-Gaussian Cholesky first; if it fails (e.g.
# non-PSD jointPrecision when pdHess = FALSE) fall back to INLA-style draws.
# Callers pass the full `res` so the INLA fallback has access to TMBobj.
.postDraws <- function(res, NDRAWS, useInla = "auto") {
    if(!exists("posteriorDraws"))
        source("code/inlaStyleDraws.R")
    tryCatch(posteriorDraws(res, NDRAWS = NDRAWS, useInla = useInla),
             error = function(e) {
                 # Last-resort cov.fixed-only fallback: keeps scoring alive
                 # when BOTH the joint Cholesky and INLA-style fail.
                 SD <- res$TMBsd
                 if(!inherits(SD, "sdreport")) return(NULL)
                 modeF <- SD$par.fixed
                 Lc    <- chol(SD$cov.fixed)
                 z     <- matrix(rnorm(length(modeF) * NDRAWS), nrow=length(modeF))
                 feDr  <- modeF + t(Lc) %*% z
                 if(length(SD$par.random) > 0) {
                     reTile <- matrix(SD$par.random, nrow=length(SD$par.random), ncol=NDRAWS)
                     rownames(reTile) <- names(SD$par.random)
                     rownames(feDr)   <- names(modeF)
                     rbind(feDr, reTile)
                 } else {
                     rownames(feDr) <- names(modeF)
                     feDr
                 }
             })
}

# ---- score hyperparameters (σ_BYM2, φ, σ_ε) on the natural scale -----------
# Returns a matrix with one row per available hyper, columns matching getScores
# output. For SPDE-generated data, truths$phi is NA -> we still record est + sd
# but leave the score columns as NA so aggregation stays well-defined.
.scoreHyper <- function(res, truths, NDRAWS) {
    SD <- res$TMBsd
    if(!inherits(SD, "sdreport")) return(NULL)
    draws <- tryCatch(.postDraws(res, NDRAWS), error = function(e) NULL)
    if(is.null(draws)) return(NULL)

    # raw-param name, natural-scale transform, truth field in `truths`
    spec <- list(
        sigmaBYM2 = list(par = "log_tau",    f = function(x) exp(-0.5*x), truth = truths$sigmaSpatial),
        phi       = list(par = "logit_phi",  f = plogis,                  truth = truths$phi),
        sigmaEps  = list(par = "log_tauEps", f = function(x) exp(-0.5*x), truth = truths$sigmaEps)
    )

    rows <- list()
    for(name in names(spec)) {
        s <- spec[[name]]
        if(!(s$par %in% rownames(draws))) next         # e.g. FE-only models lack log_tau/logit_phi
        natDraws <- s$f(draws[s$par, ])
        if(is.na(s$truth)) {
            # no truth available — record est + sd, blank the score columns
            sc <- getScores(truth = mean(natDraws), estMat = matrix(natDraws, nrow = 1),
                            significance = c(.5,.8,.9,.95), doFuzzyReject = TRUE,
                            getAverage = FALSE, na.rm = TRUE)
            sc[, c("Bias","Var","MSE","RMSE","CRPS")] <- NA
            sc[, grep("^(IntervalScore|Coverage)", colnames(sc))] <- NA
        } else {
            sc <- getScores(truth = s$truth, estMat = matrix(natDraws, nrow = 1),
                            significance = c(.5,.8,.9,.95), doFuzzyReject = TRUE,
                            getAverage = FALSE, na.rm = TRUE)
        }
        sc <- cbind(est = mean(natDraws), sd = sd(natDraws), truth = s$truth, sc)
        rownames(sc) <- name
        rows[[name]] <- sc
    }
    if(length(rows) == 0) return(NULL)
    do.call(rbind, rows)
}

# ---- score fixed effects against the DGP truth -----------------------------
.scoreFE <- function(res, NDRAWS) {
    SD <- res$TMBsd
    if(!inherits(SD, "sdreport")) return(NULL)
    draws <- tryCatch(.postDraws(res, NDRAWS), error = function(e) NULL)
    if(is.null(draws)) return(NULL)

    aRow <- draws[rownames(draws) == "alpha", , drop=FALSE]
    if(nrow(aRow) == 0) {                       # fitMd repar absorbs alpha into w_bym2Star
        wb <- draws[rownames(draws) == "w_bym2Star", , drop=FALSE]
        if(nrow(wb) > 0) aRow <- matrix(colMeans(wb), nrow=1)
    }
    bRows   <- draws[rownames(draws) == "beta", , drop=FALSE]
    feDraws <- rbind(aRow, bRows)
    if(nrow(feDraws) != length(TRUE_FE)) return(NULL)

    getScores(truth=TRUE_FE, estMat=feDraws,
              significance=c(.5,.8,.9,.95), doFuzzyReject=TRUE,
              getAverage=FALSE, na.rm=TRUE)
}

# ---- area-level prevalence scoring -----------------------------------------
.scoreArea <- function(res, areaPops, simIdx, NDRAWS) {
    if(!inherits(res$TMBsd, "sdreport")) return(NULL)

    grid <- tryCatch(
        predGrid(res$TMBsd, popMat=popMatNGAThresh, nsim=NDRAWS,
                 obj=res$TMBobj, admLevel="stratMICS"),
        error = function(e) NULL)
    if(is.null(grid)) return(NULL)

    agg    <- predArea(grid, areaVarName="area", orderedAreas=adm1@data$NAME_1)
    truth  <- areaPops[, simIdx]
    estMat <- as.matrix(agg$aggregationResults$p)
    rownames(estMat) <- agg$aggregationResults$region
    estMat <- estMat[match(names(truth), rownames(estMat)), , drop=FALSE]

    if(ncol(estMat) == 1) {
        getScores(truth=truth, est=estMat[,1],
                  significance=c(.5,.8,.9,.95), doFuzzyReject=TRUE,
                  getAverage=TRUE, na.rm=TRUE)
    } else {
        getScores(truth=truth, estMat=estMat,
                  significance=c(.5,.8,.9,.95), doFuzzyReject=TRUE,
                  getAverage=TRUE, na.rm=TRUE)
    }
}

# ---- aggregation helpers ---------------------------------------------------
.loadModelScores <- function(modName, outDir, nsim) {
    out <- list(FE = list(), Hyper = list(), Area = list(),
                fitTimes = numeric(0), scoreTimes = numeric(0),
                simIdx = integer(0))   # parallel index into FE/Hyper/Area
    for(simIdx in seq_len(nsim)) {
        f <- sprintf("%s/scores_%s_sim%d.RData", outDir, modName, simIdx)
        if(!file.exists(f)) next
        e <- new.env(); load(f, envir = e)
        # Use c(list, list(x)) form so NULL elements are properly retained.
        # x[[length(x)+1]] <- NULL silently DROPS the slot (R quirk).
        out$FE    <- c(out$FE,    list(if(exists("scoresFE",    envir=e)) e$scoresFE    else NULL))
        out$Hyper <- c(out$Hyper, list(if(exists("scoresHyper", envir=e)) e$scoresHyper else NULL))
        out$Area  <- c(out$Area,  list(if(exists("scoresArea",  envir=e)) e$scoresArea  else NULL))
        out$simIdx <- c(out$simIdx, simIdx)
        if(exists("fitTime",   envir = e)) out$fitTimes   <- c(out$fitTimes,   e$fitTime)
        if(exists("scoreTime", envir = e)) out$scoreTimes <- c(out$scoreTimes, e$scoreTime)
    }
    # Attach simIdx as element names so callers can do
    # modelData[[m]]$FE[[as.character(simIdx)]]. Defensive: only name lists
    # whose length actually matches simIdx in case anything below the append
    # path went sideways.
    if(length(out$simIdx) > 0) {
        nms <- as.character(out$simIdx)
        if(length(out$FE)    == length(nms)) names(out$FE)    <- nms
        if(length(out$Hyper) == length(nms)) names(out$Hyper) <- nms
        if(length(out$Area)  == length(nms)) names(out$Area)  <- nms
    }
    out
}
.avgScoreList <- function(lst) {
    lst <- Filter(function(x) !is.null(x), lst)
    if(length(lst) == 0) return(NULL)
    arr <- simplify2array(lapply(lst, as.matrix))
    if(length(dim(arr)) == 2) arr else apply(arr, c(1, 2), mean, na.rm = TRUE)
}
.buildAggTable <- function(modelToScoreMat) {
    rows <- list()
    for(m in names(modelToScoreMat)) {
        a <- modelToScoreMat[[m]]
        if(is.null(a)) next
        rows[[length(rows) + 1]] <- cbind(model = m, as.data.frame(a))
    }
    if(length(rows) == 0) NULL else do.call(rbind, rows)
}

# ============================================================================
# main entry point
# ============================================================================
# Core worker: fit one (sim, model) pair and write its score file.
# Used both by the serial scoreSimStudy() driver and by callr workers in
# scoreSimStudyParallel(). Pulls everything it needs from arguments — no closure
# captures — so a child R process can call it after sourcing the same files.
.scoreOneFit <- function(simIdx, modName, outFile, surveysDHS, surveysMICS,
                         intPtsMICS, model, truths, areaPops,
                         KMICS, KDHSu, KDHSr, Qgh, NDRAWS, COVS) {
    inp <- buildInputsForSim(simIdx, surveysDHS, surveysMICS, intPtsMICS, model,
                             KMICS = KMICS, KDHSu = KDHSu, KDHSr = KDHSr)

    t0  <- proc.time()[3]
    res <- tryCatch(.fitOne(modName, inp, KMICS, KDHSu, KDHSr, Qgh, COVS),
                    error = function(e) {
                        cat("    [", modName, " sim ", simIdx, "] FIT ERROR: ",
                            conditionMessage(e), "\n", sep="")
                        NULL
                    })
    if(is.null(res)) return(invisible(FALSE))
    fitTime <- (proc.time()[3] - t0)/60

    t1 <- proc.time()[3]
    scoresFE    <- tryCatch(.scoreFE(res, NDRAWS),
        error = function(e) { cat("    scoreFE error: ",    conditionMessage(e), "\n", sep=""); NULL })
    scoresHyper <- tryCatch(.scoreHyper(res, truths, NDRAWS),
        error = function(e) { cat("    scoreHyper error: ", conditionMessage(e), "\n", sep=""); NULL })
    scoresArea  <- tryCatch(.scoreArea(res, areaPops, simIdx, NDRAWS),
        error = function(e) { cat("    scoreArea error: ",  conditionMessage(e), "\n", sep=""); NULL })
    scoreTime <- (proc.time()[3] - t1)/60

    save(scoresFE, scoresHyper, scoresArea, fitTime, scoreTime, file = outFile)
    cat(sprintf("    [%s sim %d] %s  fit=%.1f score=%.1f total=%.1f min\n",
                model, simIdx, modName, fitTime, scoreTime, fitTime + scoreTime))
    invisible(TRUE)
}

scoreSimStudy <- function(model, nsim = 10, simIdxList = seq_len(nsim),
                          KMICS = 100, KDHSu = 16, KDHSr = 21,
                          Qgh = 10, NDRAWS = 1000,
                          COVS = c("urban","access","elev","distRiversLakes","normPop"),
                          regenerate = FALSE,
                          truthQuantity = c("smoothRisk","fineScalePrevalence")) {
    model         <- match.arg(model, c("spde","bym2"))
    truthQuantity <- match.arg(truthQuantity)
    tag           <- toupper(model)

    # Load model-tagged simulated populations + MICS int pts into a local env.
    simEnv <- new.env(parent = environment())
    simulateSurveys(model, nsim = nsim, regenerate = FALSE, envir = simEnv)
    micsEnv <- new.env()
    load("savedOutput/global/intPtsMICS_100.RData", envir = micsEnv)

    surveysDHS  <- simEnv$surveysDHS
    surveysMICS <- simEnv$surveysMICS
    areaPops    <- .pickAreaTruth(simEnv, truthQuantity)
    intPtsMICS  <- micsEnv$intPtsMICS
    stopifnot(length(surveysDHS) >= nsim)
    cat(sprintf("[%s] truthQuantity = \"%s\"\n", tag, truthQuantity))

    outDir <- sprintf("savedOutput/simStudy1/scores/%s", tag)
    if(!dir.exists(outDir)) dir.create(outDir, recursive = TRUE)
    truths <- modelTruths(model)

    if(isTRUE(regenerate)) {
        nRemoved <- 0
        for(m in MODELS) for(simIdx in simIdxList) {
            f <- sprintf("%s/scores_%s_sim%d.RData", outDir, m, simIdx)
            if(file.exists(f)) { file.remove(f); nRemoved <- nRemoved + 1 }
        }
        cat(sprintf("[regenerate=TRUE] Removed %d existing score files from %s/\n",
                    nRemoved, outDir))
    }

    for(simIdx in simIdxList) {
        cat(sprintf("\n##### [%s] sim %d #####\n", tag, simIdx))
        for(modName in MODELS) {
            outFile <- sprintf("%s/scores_%s_sim%d.RData", outDir, modName, simIdx)
            if(!regenerate && file.exists(outFile)) {
                cat("  [", modName, "] cached, skipping\n", sep="")
                next
            }
            .scoreOneFit(simIdx, modName, outFile,
                         surveysDHS, surveysMICS, intPtsMICS, model, truths,
                         areaPops, KMICS, KDHSu, KDHSr, Qgh, NDRAWS, COVS)
        }
    }

    cat(sprintf("\n[%s] All fits done. Aggregating scores ...\n", tag))

    modelData <- setNames(lapply(MODELS, .loadModelScores, outDir = outDir, nsim = nsim), MODELS)
    areaTab   <- .buildAggTable(lapply(modelData, function(d) .avgScoreList(d$Area)))

    cat(sprintf("\n----- [%s] Area-level scores (mean across sims) -----\n", tag))
    if(!is.null(areaTab)) print(areaTab, row.names = FALSE, digits = 4)

    cat(sprintf("\n----- [%s] Fixed-effect scores (mean across sims) -----\n", tag))
    for(m in MODELS) {
        a <- .avgScoreList(modelData[[m]]$FE)
        if(is.null(a)) next
        if(nrow(a) == length(TRUE_FE)) rownames(a) <- names(TRUE_FE)
        cat("\n[", m, "]\n", sep = "")
        print(round(a, 4))
    }

    cat(sprintf("\n----- [%s] Hyperparameter scores (mean across sims) -----\n", tag))
    for(m in MODELS) {
        a <- .avgScoreList(modelData[[m]]$Hyper)
        if(is.null(a)) next
        cat("\n[", m, "]\n", sep = "")
        print(round(a, 4))
    }

    cat(sprintf("\n----- [%s] Wall-time per (model) (minutes; mean across sims) -----\n", tag))
    timeRows <- list()
    for(m in MODELS) {
        ft <- modelData[[m]]$fitTimes
        st <- modelData[[m]]$scoreTimes
        if(length(ft) == 0 && length(st) == 0) next
        timeRows[[length(timeRows) + 1]] <- data.frame(
            model    = m,
            nSim     = length(ft),
            fitMin   = round(mean(ft), 2),
            scoreMin = round(mean(st), 2),
            totalMin = round(mean(ft) + mean(st), 2))
    }
    if(length(timeRows) > 0) print(do.call(rbind, timeRows), row.names = FALSE)

    summaryFile <- file.path(outDir, sprintf("scoresSummary_%s.RData", tag))
    save(areaTab, modelData, file = summaryFile)
    cat(sprintf("\n[%s] Aggregated tables saved to: %s\n", tag, summaryFile))

    invisible(list(areaTab = areaTab, modelData = modelData))
}

# ============================================================================
# Parallel runner: callr worker pool consuming a (simIdx, modName) queue.
# nWorkers controls degree of parallelism. Heavy fits (M_DM_BYM2, M_M_BYM2)
# are placed first in the queue so the longest-running ones start early —
# round-robin assignment then balances them across workers.
# ============================================================================
scoreSimStudyParallel <- function(model, nsim = 10, nWorkers = 4,
                                  KMICS = 100, KDHSu = 16, KDHSr = 21,
                                  Qgh = 10, NDRAWS = 1000,
                                  COVS = c("urban","access","elev","distRiversLakes","normPop"),
                                  regenerate = FALSE,
                                  truthQuantity = c("smoothRisk","fineScalePrevalence")) {
    if(!requireNamespace("callr", quietly = TRUE))
        stop("scoreSimStudyParallel requires the `callr` package")
    model         <- match.arg(model, c("spde","bym2"))
    truthQuantity <- match.arg(truthQuantity)
    tag           <- toupper(model)
    cat(sprintf("[%s] truthQuantity = \"%s\"\n", tag, truthQuantity))

    outDir <- sprintf("savedOutput/simStudy1/scores/%s", tag)
    if(!dir.exists(outDir)) dir.create(outDir, recursive = TRUE)

    if(isTRUE(regenerate)) {
        nRemoved <- 0
        for(m in MODELS) for(simIdx in seq_len(nsim)) {
            f <- sprintf("%s/scores_%s_sim%d.RData", outDir, m, simIdx)
            if(file.exists(f)) { file.remove(f); nRemoved <- nRemoved + 1 }
        }
        logsDir <- file.path(dirname(outDir), "logs")
        oldLogs <- character(0)
        if(dir.exists(logsDir)) {
            oldLogs <- list.files(
                logsDir,
                pattern = sprintf("^scoreWorker_%s_w[0-9]+\\.log$", tag),
                full.names = TRUE)
            if(length(oldLogs) > 0) file.remove(oldLogs)
        }
        cat(sprintf("[regenerate=TRUE] Removed %d score files and %d worker logs.\n",
                    nRemoved, length(oldLogs)))
    }

    # Estimated minutes per task type (empirical from earlier timing study,
    # adjusted for NDRAWS=1000). Used for LPT load balancing.
    estMin <- c(M_DM_BYM2 = 60, M_M_BYM2 = 7,
                M_DM_FE = 14, Md_FE = 13, M_D_FE = 13, M_M_FE = 13,
                Md = 1.5, M_D_BYM2 = 1.5)
    stopifnot(setequal(names(estMin), MODELS))

    tasks <- list()
    for(simIdx in seq_len(nsim)) {
        for(modName in MODELS) {
            outFile <- sprintf("%s/scores_%s_sim%d.RData", outDir, modName, simIdx)
            if(!regenerate && file.exists(outFile)) next
            tasks[[length(tasks) + 1]] <- list(simIdx = simIdx,
                                               modName = modName,
                                               outFile = outFile,
                                               est = unname(estMin[modName]))
        }
    }
    if(length(tasks) == 0) {
        cat(sprintf("[%s] all score files already present, nothing to do.\n", tag))
        return(invisible(NULL))
    }

    # LPT scheduling: sort tasks heaviest-first, then greedily assign each to
    # the currently least-loaded worker. Much better balance than round-robin
    # when one model dominates (M_DM_BYM2 ≈ 60 min, others ≤14 min).
    nW <- min(nWorkers, length(tasks))
    tasks <- tasks[order(-sapply(tasks, `[[`, "est"))]
    chunks <- vector("list", nW)
    loads  <- numeric(nW)
    for(t in tasks) {
        w <- which.min(loads)
        chunks[[w]] <- c(chunks[[w]], list(t))
        loads[w] <- loads[w] + t$est
    }
    cat(sprintf("[%s] %d tasks across %d workers; est total walltime %.0f min\n",
                tag, length(tasks), nW, max(loads)))
    for(w in seq_len(nW))
        cat(sprintf("  worker %d: %d tasks, ~%.0f min\n",
                    w, length(chunks[[w]]), loads[w]))

    parentDir <- getwd()                       # jittering project root
    codeDir   <- file.path(parentDir, "code")
    # Logs go under scores/logs/, not code/, with generative tag in the name.
    logsDir   <- file.path(dirname(outDir), "logs")
    if(!dir.exists(logsDir)) dir.create(logsDir, recursive = TRUE)

    workers <- lapply(seq_len(nW), function(w) {
        logPath <- file.path(logsDir,
                             sprintf("scoreWorker_%s_w%d.log", tag, w))
        callr::r_bg(
            func = function(taskChunk, model, KMICS, KDHSu, KDHSr,
                            Qgh, NDRAWS, COVS, codeDir, truthQuantity) {
                setwd(codeDir)
                source("setup.R")
                source("code/modFED.R")
                source("code/modFEM.R")
                source("code/modFEMD.R")
                source("code/modM_DSep.R")
                source("code/modM_MSep.R")
                source("code/modM_DMSep.R")
                source("code/modMdSep.R")
                source("code/makeInputsTMB.R")
                source("code/modBYM2.R")
                source("code/testInfrastructure.R")
                source("code/scoreSimStudy.R")

                simEnv <- new.env()
                simulateSurveys(model, nsim = max(sapply(taskChunk, `[[`, "simIdx")),
                                regenerate = FALSE, envir = simEnv)
                micsEnv <- new.env()
                load("savedOutput/global/intPtsMICS_100.RData", envir = micsEnv)
                truths   <- modelTruths(model)
                areaPops <- .pickAreaTruth(simEnv, truthQuantity)

                for(t in taskChunk) {
                    .scoreOneFit(t$simIdx, t$modName, t$outFile,
                                 simEnv$surveysDHS, simEnv$surveysMICS,
                                 micsEnv$intPtsMICS, model, truths,
                                 areaPops,
                                 KMICS, KDHSu, KDHSr, Qgh, NDRAWS, COVS)
                }
            },
            args = list(taskChunk = chunks[[w]],
                        model     = model,
                        KMICS = KMICS, KDHSu = KDHSu, KDHSr = KDHSr,
                        Qgh = Qgh, NDRAWS = NDRAWS, COVS = COVS,
                        codeDir = codeDir,
                        truthQuantity = truthQuantity),
            stdout = logPath,
            stderr = "2>&1"
        )
    })
    for(w in workers) w$wait()

    cat(sprintf("\n[%s] all workers done. Aggregating ...\n", tag))
    modelData <- setNames(lapply(MODELS, .loadModelScores,
                                 outDir = outDir, nsim = nsim), MODELS)
    areaTab   <- .buildAggTable(lapply(modelData, function(d) .avgScoreList(d$Area)))
    cat(sprintf("\n----- [%s] Area-level scores (mean across sims) -----\n", tag))
    if(!is.null(areaTab)) print(areaTab, row.names = FALSE, digits = 4)
    save(areaTab, modelData,
         file = file.path(outDir, sprintf("scoresSummary_%s.RData", tag)))
    invisible(list(areaTab = areaTab, modelData = modelData))
}
